experiment_name: "iditi_validation_study"
description: "IDITI Framework Validation Study - Three-Hypothesis Validation"
created_date: "2025-06-14"

# Component Configuration (top-level arrays as expected by analyze_batch.py)
prompt_templates:
  - "traditional_analysis"

frameworks:
  - "iditi"

weighting_methods:
  - "linear_traditional"

models:
  - "gpt-4o"

# Analysis Configuration
runs_per_combination: 1
batch_size: 10
max_retries: 3
timeout_seconds: 300
save_intermediate: true

# Output Configuration
output_config:
  save_raw_responses: true
  generate_summary: true
  create_visualizations: true
  export_formats: ["csv", "json"]

# Validation Criteria
validation_criteria:
  hypothesis_1_discriminative_validity:
    description: "Framework can distinguish dignity from tribalism rhetoric"
    dignity_threshold: 0.6
    tribalism_threshold: 0.6
    mixed_range: [0.4, 0.6]
    significance_level: 0.05
  
  hypothesis_2_ideological_agnosticism:
    description: "Framework scores content rather than political orientation"
    significance_level: 0.05
    expected_similarity: true
  
  hypothesis_3_ground_truth_alignment:
    description: "Pre-labeled texts match expected framework responses"
    extreme_controls_threshold: 0.8
    expected_patterns: true

# Expected Text Categories
text_categories:
  extreme_controls:
    - "conservative_dignity_control.txt"
    - "conservative_tribalism_control.txt"
    - "progressive_dignity_control.txt"
    - "progressive_tribalism_control.txt"
  
  mixed_controls:
    - "conservative_balanced_1.txt"
    - "conservative_balanced_2.txt"
    - "progressive_balanced_1.txt"
    - "progressive_balanced_2.txt"
  
  conservative_dignity:
    - "john_mccain_2008_concession_speech.txt"
    - "larry_hogan_2023_giia_infrastructure_speech.txt"
    - "mitt_romney_2020_impeachment_vote.txt"
    - "rick_perry_2016_alec_speech.txt"
    - "ronald_reagan_1986_challenger_address.txt"
    - "tillis_coons_2017_criminal_justice_reform.txt"
  
  conservative_tribalism:
    - "glenn_beck_immigration.txt"
    - "steve_king_house_2017.txt"
    - "steve_king_state_fair.txt"
    - "trump_nh_full.txt"
    - "trump_nh_poison.txt"
    - "vance_nat_con.txt"
  
  progressive_dignity:
    - "cory_booker_2018_first_step_act.txt"
    - "elizabeth_warren_nyc.txt"
    - "john_lewis_1963_march_washington.txt"
    - "obama_2004_dnc.txt"
    - "obama_2012_dnc_acceptance_speech.txt"
    - "tishaura_jones_2021_inaugural_address.txt"
  
  progressive_tribalism:
    - "aoc_2025_fighting_oligarchy_rally.txt"
    - "barron_electoral_politics_radical_action_2009.txt"
    - "bernie_sanders_2025_fighting_oligarchy_rally.txt"
    - "diangelo_white_fragility_oakland_2019.txt"
    - "ibram_x_kendi_belonging.txt"
    - "malcom_x_ballot_or_bullet.txt" 