content_hash: c62c9447dc9bec6f9bbb38dd0e3599a2329832e41cfa9fd410bada63a24cc262
ingestion_date: '2025-06-19T15:57:47.536808'
ingestion_method: unified_asset_pipeline
source_path: research_workspaces/june_2025_research_dev_workspace/frameworks/moral_foundations_theory
source_type: development_workspace
