repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: []
  - repo: local
    hooks:
      - id: terminology-lint
        name: terminology-lint
        entry: python3 scripts/applications/terminology_lint.py
        language: system
        types: [python, text, yaml]
