[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "discernus"
version = "0.2.0"
description = "Discernus Computational Social Science Research Platform"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Discernus Team"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Text Processing :: Linguistic",
]

dependencies = [
    # Core Discernus dependencies (ultra-thin approach)
    "GitPython>=3.1.0",           # Conversation logging with git transparency
    "python-dotenv>=1.0.0",       # Environment configuration
    "click>=8.0.0",               # CLI framework
    
    # LLM Gateway dependencies (minimal)
    "litellm>=1.73.0",           # Multi-provider LLM access
    "requests>=2.28.0",          # HTTP requests for LLM APIs
    
    # Redis coordination
    "redis>=4.0.0",              # Redis client
    "PyYAML>=6.0.0",             # YAML parsing for configurations
    
    # Academic/Scientific computing (when needed)
    "numpy>=1.24.0",             # Numerical computing
    "pandas>=2.0.0",             # Data analysis
    "scipy>=1.10.0",             # Scientific computing
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio", 
    "black",
    "isort",
    "flake8",
]

academic = [
    # Additional scientific computing packages
    "statsmodels>=0.14.0",       # Statistical analysis
    "scikit-learn>=1.2.0",       # Machine learning
    "plotly>=5.14.0",            # Interactive visualizations
    "jupyter>=1.0.0",            # Notebook environment
]

[project.urls]
Homepage = "https://github.com/discernus/discernus"
Repository = "https://github.com/discernus/discernus.git"
Issues = "https://github.com/discernus/discernus/issues"

[project.scripts]
discernus = "discernus.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["discernus*"]

[tool.black]
line-length = 120
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
testpaths = ["discernus/tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"] 
python_functions = ["test_*"]
addopts = "-v" 