asset_type: !!python/object/apply:__main__.AssetType
- framework
content_hash: d1dbbd70b4290435607f5057f7cd06670ad0116249871c4a3eb575e67d03b33a
created_at: 2025-06-19 15:57:47.521456
development_path: research_workspaces/june_2025_research_dev_workspace/frameworks/three_wells_political
format_version: yaml_v1.0
name: framework
storage_path: asset_storage/framework/d1/db/d1dbbd70b4290435607f5057f7cd06670ad0116249871c4a3eb575e67d03b33a
validation_status: pending
version: auto
