content_hash: d1dbbd70b4290435607f5057f7cd06670ad0116249871c4a3eb575e67d03b33a
ingestion_date: '2025-06-19T15:57:47.521881'
ingestion_method: unified_asset_pipeline
source_path: research_workspaces/june_2025_research_dev_workspace/frameworks/three_wells_political
source_type: development_workspace
