/* gen winner loser codes */
gen prvote=.    
replace prvote= 0  if  prtvalt1 == 1
replace prvote= 0  if  prtvalt1 == 2
replace prvote= 2  if  prtvalt1 == 3
replace prvote= 0  if  prtvalt1 == 4
replace prvote= 0  if  prtvalt1 == 5
replace prvote= 0  if  prtvalt1 == 6
replace prvote= 2  if  prtvalt1 == 7
replace prvote= 1  if  prtvalt1 == 8
replace prvote= 2  if  prtvalt1 == 9
replace prvote= 0  if  prtvalt1 == 10
replace prvote= 0  if  prtvalt1 == 11
replace prvote= 0  if  prtvalt1 == 12
replace prvote= 0  if  prtvalt1 == 13
replace prvote= 0  if  prtvalt1 == 14
replace prvote= 0  if  prtvalt1 == 15
replace prvote= 0  if  prtvalt1 == 16
replace prvote= 0  if  prtvalt1 == 17
replace prvote= 0  if  prtvalt1 == 18
replace prvote= 6  if  prtvalt1 == 44
replace prvote= 4  if  prtvalt1 == 55
replace prvote= 7  if  prtvalt1 == 66
replace prvote= 3  if  prtvalt1 == 77
replace prvote= 4  if  prtvalt1 == 88
replace prvote= 5  if  prtvalt1 == 99
replace prvote= 0  if  prtvdde2 == 1
replace prvote= 1  if  prtvdde2 == 2
replace prvote= 0  if  prtvdde2 == 3
replace prvote= 2  if  prtvdde2 == 4
replace prvote= 0  if  prtvdde2 == 5
replace prvote= 0  if  prtvdde2 == 6
replace prvote= 0  if  prtvdde2 == 7
replace prvote= 0  if  prtvdde2 == 8
replace prvote= 0  if  prtvdde2 == 9
replace prvote= 7  if  prtvdde2 == 66
replace prvote= 3  if  prtvdde2 == 77
replace prvote= 4  if  prtvdde2 == 88
replace prvote= 5  if  prtvdde2 == 99
replace prvote= 1  if  prtvtacy == 1
replace prvote= 0  if  prtvtacy == 2
replace prvote= 0  if  prtvtacy == 3
replace prvote= 0  if  prtvtacy == 4
replace prvote= 0  if  prtvtacy == 5
replace prvote= 0  if  prtvtacy == 6
replace prvote= 0  if  prtvtacy == 7
replace prvote= 7  if  prtvtacy == 66
replace prvote= 3  if  prtvtacy == 77
replace prvote= 4  if  prtvtacy == 88
replace prvote= 5  if  prtvtacy == 99
replace prvote= 0  if  prtvtaie == 1
replace prvote= 1  if  prtvtaie == 2
replace prvote= 0  if  prtvtaie == 3
replace prvote= 0  if  prtvtaie == 4
replace prvote= 2  if  prtvtaie == 5
replace prvote= 0  if  prtvtaie == 6
replace prvote= 0  if  prtvtaie == 7
replace prvote= 0  if  prtvtaie == 8
replace prvote= 0  if  prtvtaie == 9
replace prvote= 0  if  prtvtaie == 10
replace prvote= 7  if  prtvtaie == 66
replace prvote= 3  if  prtvtaie == 77
replace prvote= 4  if  prtvtaie == 88
replace prvote= 5  if  prtvtaie == 99
replace prvote= 1  if  prtvtais == 1
replace prvote= 0  if  prtvtais == 2
replace prvote= 0  if  prtvtais == 3
replace prvote= 2  if  prtvtais == 4
replace prvote= 0  if  prtvtais == 5
replace prvote= 0  if  prtvtais == 6
replace prvote= 0  if  prtvtais == 7
replace prvote= 6  if  prtvtais == 8
replace prvote= 7  if  prtvtais == 66
replace prvote= 3  if  prtvtais == 77
replace prvote= 4  if  prtvtais == 88
replace prvote= 5  if  prtvtais == 99
replace prvote= 0  if  prtvtal == 1
replace prvote= 1  if  prtvtal == 2
replace prvote= 0  if  prtvtal == 3
replace prvote= 0  if  prtvtal == 4
replace prvote= 0  if  prtvtal == 5
replace prvote= 0  if  prtvtal == 6
replace prvote= 0  if  prtvtal == 7
replace prvote= 0  if  prtvtal == 8
replace prvote= 7  if  prtvtal == 66
replace prvote= 3  if  prtvtal == 77
replace prvote= 4  if  prtvtal == 88
replace prvote= 5  if  prtvtal == 99
replace prvote= 0  if  prtvtano == 1
replace prvote= 2  if  prtvtano == 2
replace prvote= 1  if  prtvtano == 3
replace prvote= 0  if  prtvtano == 4
replace prvote= 0  if  prtvtano == 5
replace prvote= 2  if  prtvtano == 6
replace prvote= 0  if  prtvtano == 7
replace prvote= 0  if  prtvtano == 8
replace prvote= 0  if  prtvtano == 9
replace prvote= 0  if  prtvtano == 10
replace prvote= 7  if  prtvtano == 66
replace prvote= 3  if  prtvtano == 77
replace prvote= 4  if  prtvtano == 88
replace prvote= 5  if  prtvtano == 99
replace prvote= 0  if  prtvtbil == 1
replace prvote= 1  if  prtvtbil == 2
replace prvote= 0  if  prtvtbil == 3
replace prvote= 0  if  prtvtbil == 4
replace prvote= 0  if  prtvtbil == 5
replace prvote= 2  if  prtvtbil == 6
replace prvote= 0  if  prtvtbil == 7
replace prvote= 0  if  prtvtbil == 8
replace prvote= 2  if  prtvtbil == 9
replace prvote= 2  if  prtvtbil == 10
replace prvote= 0  if  prtvtbil == 11
replace prvote= 0  if  prtvtbil == 12
replace prvote= 0  if  prtvtbil == 13
replace prvote= 0  if  prtvtbil == 14
replace prvote= 0  if  prtvtbil == 15
replace prvote= 0  if  prtvtbil == 16
replace prvote= 0  if  prtvtbil == 17
replace prvote= 6  if  prtvtbil == 18
replace prvote= 3  if  prtvtbil == 19
replace prvote= 7  if  prtvtbil == 66
replace prvote= 3  if  prtvtbil == 77
replace prvote= 4  if  prtvtbil == 88
replace prvote= 5  if  prtvtbil == 99
replace prvote= 1  if  prtvtbit == 1
replace prvote= 0  if  prtvtbit == 2
replace prvote= 0  if  prtvtbit == 3
replace prvote= 0  if  prtvtbit == 4
replace prvote= 2  if  prtvtbit == 5
replace prvote= 2  if  prtvtbit == 6
replace prvote= 0  if  prtvtbit == 7
replace prvote= 2  if  prtvtbit == 8
replace prvote= 0  if  prtvtbit == 9
replace prvote= 0  if  prtvtbit == 10
replace prvote= 2  if  prtvtbit == 11
replace prvote= 0  if  prtvtbit == 12
replace prvote= 0  if  prtvtbit == 13
replace prvote= 0  if  prtvtbit == 14
replace prvote= 7  if  prtvtbit == 66
replace prvote= 3  if  prtvtbit == 77
replace prvote= 4  if  prtvtbit == 88
replace prvote= 5  if  prtvtbit == 99
replace prvote= 0  if  prtvtbpt == 1
replace prvote= 2  if  prtvtbpt == 2
replace prvote= 0  if  prtvtbpt == 3
replace prvote= 0  if  prtvtbpt == 4
replace prvote= 0  if  prtvtbpt == 5
replace prvote= 0  if  prtvtbpt == 6
replace prvote= 0  if  prtvtbpt == 7
replace prvote= 0  if  prtvtbpt == 8
replace prvote= 0  if  prtvtbpt == 9
replace prvote= 1  if  prtvtbpt == 10
replace prvote= 0  if  prtvtbpt == 11
replace prvote= 6  if  prtvtbpt == 12
replace prvote= 0  if  prtvtbpt == 13
replace prvote= 7  if  prtvtbpt == 66
replace prvote= 3  if  prtvtbpt == 77
replace prvote= 4  if  prtvtbpt == 88
replace prvote= 5  if  prtvtbpt == 99
replace prvote= 2  if  prtvtbse == 1
replace prvote= 2  if  prtvtbse == 2
replace prvote= 2  if  prtvtbse == 3
replace prvote= 0  if  prtvtbse == 4
replace prvote= 1  if  prtvtbse == 5
replace prvote= 0  if  prtvtbse == 6
replace prvote= 0  if  prtvtbse == 7
replace prvote= 0  if  prtvtbse == 8
replace prvote= 0  if  prtvtbse == 9
replace prvote= 0  if  prtvtbse == 10
replace prvote= 0  if  prtvtbse == 11
replace prvote= 7  if  prtvtbse == 66
replace prvote= 3  if  prtvtbse == 77
replace prvote= 4  if  prtvtbse == 88
replace prvote= 5  if  prtvtbse == 99
replace prvote= 2  if  prtvtcbe == 2
replace prvote= 0  if  prtvtcbe == 3
replace prvote= 0  if  prtvtcbe == 4
replace prvote= 2  if  prtvtcbe == 5
replace prvote= 0  if  prtvtcbe == 6
replace prvote= 0  if  prtvtcbe == 7
replace prvote= 2  if  prtvtcbe == 8
replace prvote= 2  if  prtvtcbe == 9
replace prvote= 0  if  prtvtcbe == 10
replace prvote= 0  if  prtvtcbe == 11
replace prvote= 2  if  prtvtcbe == 12
replace prvote= 1  if  prtvtcbe == 13
replace prvote= 0  if  prtvtcbe == 14
replace prvote= 0  if  prtvtcbe == 15
replace prvote= 0  if  prtvtcbe == 16
replace prvote= 6  if  prtvtcbe == 17
replace prvote= 6  if  prtvtcbe == 18
replace prvote= 7  if  prtvtcbe == 66
replace prvote= 3  if  prtvtcbe == 77
replace prvote= 4  if  prtvtcbe == 88
replace prvote= 5  if  prtvtcbe == 99
replace prvote= 1  if  prtvtcbg == 1
replace prvote= 0  if  prtvtcbg == 2
replace prvote= 0  if  prtvtcbg == 3
replace prvote= 0  if  prtvtcbg == 4
replace prvote= 0  if  prtvtcbg == 5
replace prvote= 0  if  prtvtcbg == 6
replace prvote= 0  if  prtvtcbg == 7
replace prvote= 0  if  prtvtcbg == 8
replace prvote= 0  if  prtvtcbg == 9
replace prvote= 0  if  prtvtcbg == 10
replace prvote= 0  if  prtvtcbg == 11
replace prvote= 0  if  prtvtcbg == 12
replace prvote= 0  if  prtvtcbg == 13
replace prvote= 7  if  prtvtcbg == 66
replace prvote= 3  if  prtvtcbg == 77
replace prvote= 4  if  prtvtcbg == 88
replace prvote= 5  if  prtvtcbg == 99
replace prvote= 0  if  prtvtccz == 1
replace prvote= 0  if  prtvtccz == 2
replace prvote= 2  if  prtvtccz == 3
replace prvote= 2  if  prtvtccz == 4
replace prvote= 1  if  prtvtccz == 5
replace prvote= 0  if  prtvtccz == 8
replace prvote= 7  if  prtvtccz == 66
replace prvote= 3  if  prtvtccz == 77
replace prvote= 4  if  prtvtccz == 88
replace prvote= 5  if  prtvtccz == 99
replace prvote= 1  if  prtvtcdk == 1
replace prvote= 2  if  prtvtcdk == 2
replace prvote= 0  if  prtvtcdk == 3
replace prvote= 2  if  prtvtcdk == 4
replace prvote= 0  if  prtvtcdk == 5
replace prvote= 0  if  prtvtcdk == 6
replace prvote= 0  if  prtvtcdk == 7
replace prvote= 0  if  prtvtcdk == 8
replace prvote= 0  if  prtvtcdk == 9
replace prvote= 0  if  prtvtcdk == 10
replace prvote= 7  if  prtvtcdk == 66
replace prvote= 3  if  prtvtcdk == 77
replace prvote= 4  if  prtvtcdk == 88
replace prvote= 5  if  prtvtcdk == 99
replace prvote= 1  if  prtvtces == 1
replace prvote= 0  if  prtvtces == 2
replace prvote= 0  if  prtvtces == 3
replace prvote= 0  if  prtvtces == 4
replace prvote= 0  if  prtvtces == 5
replace prvote= 0  if  prtvtces == 6
replace prvote= 0  if  prtvtces == 7
replace prvote= 0  if  prtvtces == 8
replace prvote= 0  if  prtvtces == 9
replace prvote= 0  if  prtvtces == 10
replace prvote= 0  if  prtvtces == 11
replace prvote= 0  if  prtvtces == 12
replace prvote= 0  if  prtvtces == 13
replace prvote= 0  if  prtvtces == 14
replace prvote= 6  if  prtvtces == 15
replace prvote= 6  if  prtvtces == 16
replace prvote= 7  if  prtvtces == 66
replace prvote= 3  if  prtvtces == 77
replace prvote= 4  if  prtvtces == 88
replace prvote= 5  if  prtvtces == 99
replace prvote= 1  if  prtvtcfi == 1
replace prvote= 2  if  prtvtcfi == 2
replace prvote= 0  if  prtvtcfi == 3
replace prvote= 0  if  prtvtcfi == 4
replace prvote= 2  if  prtvtcfi == 5
replace prvote= 0  if  prtvtcfi == 6
replace prvote= 0  if  prtvtcfi == 7
replace prvote= 0  if  prtvtcfi == 8
replace prvote= 0  if  prtvtcfi == 9
replace prvote= 0  if  prtvtcfi == 10
replace prvote= 0  if  prtvtcfi == 11
replace prvote= 2  if  prtvtcfi == 12
replace prvote= 2  if  prtvtcfi == 13
replace prvote= 2  if  prtvtcfi == 14
replace prvote= 0  if  prtvtcfi == 15
replace prvote= 0  if  prtvtcfi == 16
replace prvote= 0  if  prtvtcfi == 17
replace prvote= 0  if  prtvtcfi == 18
replace prvote= 7  if  prtvtcfi == 66
replace prvote= 3  if  prtvtcfi == 77
replace prvote= 4  if  prtvtcfi == 88
replace prvote= 5  if  prtvtcfi == 99
replace prvote= 0  if  prtvtcfr == 1
replace prvote= 0  if  prtvtcfr == 2
replace prvote= 0  if  prtvtcfr == 3
replace prvote= 0  if  prtvtcfr == 4
replace prvote= 0  if  prtvtcfr == 5
replace prvote= 0  if  prtvtcfr == 6
replace prvote= 2  if  prtvtcfr == 7
replace prvote= 0  if  prtvtcfr == 8
replace prvote= 1  if  prtvtcfr == 9
replace prvote= 0  if  prtvtcfr == 10
replace prvote= 0  if  prtvtcfr == 11
replace prvote= 2  if  prtvtcfr == 12
replace prvote= 0  if  prtvtcfr == 13
replace prvote= 0  if  prtvtcfr == 14
replace prvote= 6  if  prtvtcfr == 15
replace prvote= 6  if  prtvtcfr == 16
replace prvote= 7  if  prtvtcfr == 66
replace prvote= 3  if  prtvtcfr == 77
replace prvote= 4  if  prtvtcfr == 88
replace prvote= 5  if  prtvtcfr == 99
replace prvote= 0  if  prtvtcpl == 1
replace prvote= 1  if  prtvtcpl == 2
replace prvote= 0  if  prtvtcpl == 3
replace prvote= 0  if  prtvtcpl == 4
replace prvote= 2  if  prtvtcpl == 5
replace prvote= 0  if  prtvtcpl == 6
replace prvote= 0  if  prtvtcpl == 7
replace prvote= 0  if  prtvtcpl == 8
replace prvote= 0  if  prtvtcpl == 9
replace prvote= 7  if  prtvtcpl == 66
replace prvote= 3  if  prtvtcpl == 77
replace prvote= 4  if  prtvtcpl == 88
replace prvote= 5  if  prtvtcpl == 99
replace prvote= 1  if  prtvtcru == 1
replace prvote= 0  if  prtvtcru == 2
replace prvote= 0  if  prtvtcru == 3
replace prvote= 0  if  prtvtcru == 6
replace prvote= 0  if  prtvtcru == 11
replace prvote= 0  if  prtvtcru == 12
replace prvote= 0  if  prtvtcru == 16
replace prvote= 7  if  prtvtcru == 66
replace prvote= 3  if  prtvtcru == 77
replace prvote= 4  if  prtvtcru == 88
replace prvote= 5  if  prtvtcru == 99
replace prvote= 0  if  prtvtcsk == 1
replace prvote= 0  if  prtvtcsk == 2
replace prvote= 1  if  prtvtcsk == 3
replace prvote= 0  if  prtvtcsk == 4
replace prvote= 0  if  prtvtcsk == 5
replace prvote= 0  if  prtvtcsk == 6
replace prvote= 0  if  prtvtcsk == 7
replace prvote= 7  if  prtvtcsk == 66
replace prvote= 3  if  prtvtcsk == 77
replace prvote= 4  if  prtvtcsk == 88
replace prvote= 5  if  prtvtcsk == 99
replace prvote= 0  if  prtvtcua == 1
replace prvote= 0  if  prtvtcua == 2
replace prvote= 0  if  prtvtcua == 3
replace prvote= 0  if  prtvtcua == 4
replace prvote= 1  if  prtvtcua == 5
replace prvote= 0  if  prtvtcua == 8
replace prvote= 7  if  prtvtcua == 66
replace prvote= 3  if  prtvtcua == 77
replace prvote= 4  if  prtvtcua == 88
replace prvote= 5  if  prtvtcua == 99
replace prvote= 2  if  prtvtdch == 1
replace prvote= 2  if  prtvtdch == 2
replace prvote= 2  if  prtvtdch == 3
replace prvote= 2  if  prtvtdch == 4
replace prvote= 0  if  prtvtdch == 5
replace prvote= 0  if  prtvtdch == 6
replace prvote= 2  if  prtvtdch == 7
replace prvote= 0  if  prtvtdch == 8
replace prvote= 0  if  prtvtdch == 9
replace prvote= 0  if  prtvtdch == 10
replace prvote= 0  if  prtvtdch == 11
replace prvote= 0  if  prtvtdch == 12
replace prvote= 0  if  prtvtdch == 13
replace prvote= 0  if  prtvtdch == 14
replace prvote= 0  if  prtvtdch == 15
replace prvote= 0  if  prtvtdch == 16
replace prvote= 0  if  prtvtdch == 17
replace prvote= 6  if  prtvtdch == 19
replace prvote= 6  if  prtvtdch == 20
replace prvote= 7  if  prtvtdch == 66
replace prvote= 3  if  prtvtdch == 77
replace prvote= 4  if  prtvtdch == 88
replace prvote= 5  if  prtvtdch == 99
replace prvote= 2  if  prtvtdee == 1
replace prvote= 0  if  prtvtdee == 2
replace prvote= 1  if  prtvtdee == 3
replace prvote= 0  if  prtvtdee == 4
replace prvote= 0  if  prtvtdee == 5
replace prvote= 0  if  prtvtdee == 6
replace prvote= 0  if  prtvtdee == 7
replace prvote= 0  if  prtvtdee == 8
replace prvote= 0  if  prtvtdee == 9
replace prvote= 0  if  prtvtdee == 10
replace prvote= 0  if  prtvtdee == 11
replace prvote= 7  if  prtvtdee == 66
replace prvote= 3  if  prtvtdee == 77
replace prvote= 4  if  prtvtdee == 88
replace prvote= 5  if  prtvtdee == 99
replace prvote= 0  if  prtvtdhu == 1
replace prvote= 0  if  prtvtdhu == 2
replace prvote= 1  if  prtvtdhu == 3
replace prvote= 0  if  prtvtdhu == 4
replace prvote= 0  if  prtvtdhu == 5
replace prvote= 0  if  prtvtdhu == 6
replace prvote= 0  if  prtvtdhu == 7
replace prvote= 0  if  prtvtdhu == 8
replace prvote= 0  if  prtvtdhu == 9
replace prvote= 0  if  prtvtdhu == 10
replace prvote= 0  if  prtvtdhu == 11
replace prvote= 0  if  prtvtdhu == 12
replace prvote= 0  if  prtvtdhu == 13
replace prvote= 0  if  prtvtdhu == 55
replace prvote= 7  if  prtvtdhu == 66
replace prvote= 3  if  prtvtdhu == 77
replace prvote= 4  if  prtvtdhu == 88
replace prvote= 5  if  prtvtdhu == 99
replace prvote= 2  if  prtvtdsi == 1
replace prvote= 0  if  prtvtdsi == 2
replace prvote= 2  if  prtvtdsi == 3
replace prvote= 1  if  prtvtdsi == 4
replace prvote= 2  if  prtvtdsi == 5
replace prvote= 0  if  prtvtdsi == 6
replace prvote= 0  if  prtvtdsi == 7
replace prvote= 2  if  prtvtdsi == 8
replace prvote= 0  if  prtvtdsi == 9
replace prvote= 0  if  prtvtdsi == 10
replace prvote= 0  if  prtvtdsi == 11
replace prvote= 0  if  prtvtdsi == 12
replace prvote= 7  if  prtvtdsi == 66
replace prvote= 3  if  prtvtdsi == 77
replace prvote= 4  if  prtvtdsi == 88
replace prvote= 5  if  prtvtdsi == 99
replace prvote= 1  if  prtvtenl == 1
replace prvote= 2  if  prtvtenl == 2
replace prvote= 0  if  prtvtenl == 3
replace prvote= 0  if  prtvtenl == 4
replace prvote= 0  if  prtvtenl == 5
replace prvote= 0  if  prtvtenl == 6
replace prvote= 0  if  prtvtenl == 7
replace prvote= 0  if  prtvtenl == 8
replace prvote= 0  if  prtvtenl == 9
replace prvote= 0  if  prtvtenl == 10
replace prvote= 0  if  prtvtenl == 11
replace prvote= 0  if  prtvtenl == 12
replace prvote= 0  if  prtvtenl == 13
replace prvote= 6  if  prtvtenl == 14
replace prvote= 7  if  prtvtenl == 66
replace prvote= 3  if  prtvtenl == 77
replace prvote= 4  if  prtvtenl == 88
replace prvote= 5  if  prtvtenl == 99
replace prvote= 1  if  prtvtgb == 1
replace prvote= 0  if  prtvtgb == 2
replace prvote= 2  if  prtvtgb == 3
replace prvote= 0  if  prtvtgb == 4
replace prvote= 0  if  prtvtgb == 5
replace prvote= 0  if  prtvtgb == 6
replace prvote= 0  if  prtvtgb == 7
replace prvote= 0  if  prtvtgb == 11
replace prvote= 0  if  prtvtgb == 12
replace prvote= 0  if  prtvtgb == 13
replace prvote= 0  if  prtvtgb == 14
replace prvote= 0  if  prtvtgb == 15
replace prvote= 0  if  prtvtgb == 16
replace prvote= 0  if  prtvtgb == 17
replace prvote= 0  if  prtvtgb == 18
replace prvote= 0  if  prtvtgb == 19
replace prvote= 0  if  prtvtgb == 20
replace prvote= 0  if  prtvtgb == 21
replace prvote= 0  if  prtvtgb == 22
replace prvote= 7  if  prtvtgb == 66
replace prvote= 3  if  prtvtgb == 77
replace prvote= 4  if  prtvtgb == 88
replace prvote= 5  if  prtvtgb == 99
replace prvote= 0  if  prtvtxk == 1
replace prvote= 1  if  prtvtxk == 2
replace prvote= 0  if  prtvtxk == 3
replace prvote= 0  if  prtvtxk == 4
replace prvote= 0  if  prtvtxk == 5
replace prvote= 2  if  prtvtxk == 6
replace prvote= 0  if  prtvtxk == 7
replace prvote= 0  if  prtvtxk == 8
replace prvote= 0  if  prtvtxk == 9
replace prvote= 0  if  prtvtxk == 10
replace prvote= 0  if  prtvtxk == 11
replace prvote= 0  if  prtvtxk == 12
replace prvote= 2  if  prtvtxk == 13
replace prvote= 7  if  prtvtxk == 66
replace prvote= 3  if  prtvtxk == 77
replace prvote= 4  if  prtvtxk == 88
replace prvote= 5  if  prtvtxk == 99


label var prvote "outcome of last election"

label define prvote 0 "Loser" 1 "Executive" 2 "Cabinet" 3 "Refused" 4 "Don't Know" 5 "No answer" 6 "Blank or Null" 7 "Not Aplicable", replace
label values prvote prvote

gen prvote2=prvote
replace prvote2=. if vote>=3
replace prvote2=. if prtvalt3==33
label define prvote2 0 "Loser" 1 "Executive" 2 "Cabinet" 3 "Refused" 4 "Don't Know" 5 "No answer" 6 "Blank or Null" 7 "Abstained", replace
label values prvote2 prvote2
label var prvote2 "outcome of last election no n/a"


