gen party_ideology=.   
replace party_ideology= 1 if  prtvtcbe == 6
replace party_ideology= 1 if  prtvtcbe == 14
replace party_ideology= 1 if  prtvtdch == 2
replace party_ideology= 1 if  prtvtdch == 5
replace party_ideology= 1 if  prtvtdch == 11
replace party_ideology= 1 if  prtvtdch == 14
replace party_ideology= 1 if  prtvtacy == 1
replace party_ideology= 1 if  prtvtccz == 1
replace party_ideology= 1 if  prtvdde2 == 5
replace party_ideology= 1 if  prtvtcdk == 9
replace party_ideology= 1 if  prtvtdee == 6
replace party_ideology= 1 if  prtvtdee == 9
replace party_ideology= 1 if  prtvtces == 4
replace party_ideology= 1 if  prtvtces == 5
replace party_ideology= 1 if  prtvtces == 11
replace party_ideology= 1 if  prtvtcfi == 14
replace party_ideology= 1 if  prtvtcfi == 15
replace party_ideology= 1 if  prtvtcfi == 16
replace party_ideology= 1 if  prtvtcfi == 17
replace party_ideology= 1 if  prtvtcfr == 4
replace party_ideology= 1 if  prtvtcfr == 5
replace party_ideology= 1 if  prtvtcfr == 6
replace party_ideology= 1 if  prtvtdhu == 10
replace party_ideology= 1 if  prtvtaie == 6
replace party_ideology= 1 if  prtvtaie == 7
replace party_ideology= 1 if  prtvtaie == 8
replace party_ideology= 1 if  prtvtaie == 9
replace party_ideology= 1 if  prtvtais == 4
replace party_ideology= 1 if  prtvtbit == 2
replace party_ideology= 1 if  prtvtbit == 3
replace party_ideology= 1 if  prtvalt1 == 4
replace party_ideology= 1 if  prtvalt1 == 6
replace party_ideology= 1 if  prtvalt1 == 13
replace party_ideology= 1 if  prtvtenl == 5
replace party_ideology= 1 if  prtvtano == 2
replace party_ideology= 1 if  prtvtano == 6
replace party_ideology= 1 if  prtvtcpl == 4
replace party_ideology= 1 if  prtvtbpt == 1
replace party_ideology= 1 if  prtvtbpt == 3
replace party_ideology= 1 if  prtvtbpt == 4
replace party_ideology= 1 if  prtvtbpt == 9
replace party_ideology= 1 if  prtvtbse == 7
replace party_ideology= 1 if  prtvtbse == 8
replace party_ideology= 1 if  prtvtdsi == 11
replace party_ideology= 2 if  prtvtcbe == 5
replace party_ideology= 2 if  prtvtcbe == 10
replace party_ideology= 2 if  prtvtcbe == 13
replace party_ideology= 2 if  prtvtcbg == 2
replace party_ideology= 2 if  prtvtdch == 16
replace party_ideology= 2 if  prtvtccz == 2
replace party_ideology= 2 if  prtvdde2 == 1
replace party_ideology= 2 if  prtvdde2 == 3
replace party_ideology= 2 if  prtvdde2 == 8
replace party_ideology= 2 if  prtvtcdk == 4
replace party_ideology= 2 if  prtvtdee == 2
replace party_ideology= 2 if  prtvtdee == 5
replace party_ideology= 2 if  prtvtces == 2
replace party_ideology= 2 if  prtvtces == 8
replace party_ideology= 2 if  prtvtces == 9
replace party_ideology= 2 if  prtvtces == 13
replace party_ideology= 2 if  prtvtcfi == 11
replace party_ideology= 2 if  prtvtcfr == 7
replace party_ideology= 2 if  prtvtcfr == 9
replace party_ideology= 2 if  prtvtcfr == 12
replace party_ideology= 2 if  prtvtgb == 4
replace party_ideology= 2 if  prtvtgb == 5
replace party_ideology= 2 if  prtvtgb == 6
replace party_ideology= 2 if  prtvtgb == 13
replace party_ideology= 2 if  prtvtgb == 14
replace party_ideology= 2 if  prtvtgb == 16
replace party_ideology= 2 if  prtvtdhu == 5
replace party_ideology= 2 if  prtvtdhu == 8
replace party_ideology= 2 if  prtvtaie == 3
replace party_ideology= 2 if  prtvtaie == 5
replace party_ideology= 2 if  prtvtais == 1
replace party_ideology= 2 if  prtvtais == 6
replace party_ideology= 2 if  prtvtbit == 1
replace party_ideology= 2 if  prtvalt1 == 14
replace party_ideology= 2 if  prtvtenl == 2
replace party_ideology= 2 if  prtvtenl == 7
replace party_ideology= 2 if  prtvtenl == 10
replace party_ideology= 2 if  prtvtano == 3
replace party_ideology= 2 if  prtvtcpl == 7
replace party_ideology= 2 if  prtvtcpl == 8
replace party_ideology= 2 if  prtvtbpt == 6
replace party_ideology= 2 if  prtvtbse == 4
replace party_ideology= 2 if  prtvtbse == 6
replace party_ideology= 2 if  prtvtdsi == 6
replace party_ideology= 2 if  prtvtdsi == 7
replace party_ideology= 2 if  prtvtdsi == 9
replace party_ideology= 2 if  prtvtcsk == 3
replace party_ideology= 3 if  prtvtcbe == 2
replace party_ideology= 3 if  prtvtcbe == 9
replace party_ideology= 3 if  prtvtcbg == 7
replace party_ideology= 3 if  prtvtcbg == 12
replace party_ideology= 3 if  prtvtdch == 6
replace party_ideology= 3 if  prtvtdch == 8
replace party_ideology= 3 if  prtvtdch == 13
replace party_ideology= 3 if  prtvtacy == 5
replace party_ideology= 3 if  prtvtacy == 6
replace party_ideology= 3 if  prtvtccz == 4
replace party_ideology= 3 if  prtvtcdk == 1
replace party_ideology= 3 if  prtvtcdk == 2
replace party_ideology= 3 if  prtvtdee == 4
replace party_ideology= 3 if  prtvtces == 6
replace party_ideology= 3 if  prtvtcfi == 3
replace party_ideology= 3 if  prtvtcfi == 4
replace party_ideology= 3 if  prtvtcfi == 8
replace party_ideology= 3 if  prtvtcfi == 12
replace party_ideology= 3 if  prtvtcfi == 13
replace party_ideology= 3 if  prtvtcfr == 1
replace party_ideology= 3 if  prtvtcfr == 11
replace party_ideology= 3 if  prtvtgb == 2
replace party_ideology= 3 if  prtvtgb == 3
replace party_ideology= 3 if  prtvtgb == 15
replace party_ideology= 3 if  prtvtdhu == 1
replace party_ideology= 3 if  prtvtdhu == 9
replace party_ideology= 3 if  prtvtdhu == 13
replace party_ideology= 3 if  prtvtaie == 1
replace party_ideology= 3 if  prtvtbit == 4
replace party_ideology= 3 if  prtvtbit == 5
replace party_ideology= 3 if  prtvtbit == 6
replace party_ideology= 3 if  prtvtbit == 11
replace party_ideology= 3 if  prtvalt1 == 3
replace party_ideology= 3 if  prtvalt1 == 7
replace party_ideology= 3 if  prtvalt1 == 8
replace party_ideology= 3 if  prtvtenl == 6
replace party_ideology= 3 if  prtvtenl == 8
replace party_ideology= 3 if  prtvtenl == 11
replace party_ideology= 3 if  prtvtenl == 12
replace party_ideology= 3 if  prtvtano == 4
replace party_ideology= 3 if  prtvtano == 5
replace party_ideology= 3 if  prtvtcpl == 5
replace party_ideology= 3 if  prtvtbpt == 5
replace party_ideology= 3 if  prtvtbpt == 11
replace party_ideology= 3 if  prtvtbse == 9
replace party_ideology= 3 if  prtvtdsi == 1
replace party_ideology= 3 if  prtvtdsi == 2
replace party_ideology= 3 if  prtvtdsi == 8
replace party_ideology= 4 if  prtvtcbe == 3
replace party_ideology= 4 if  prtvtcbe == 8
replace party_ideology= 4 if  prtvtcbe == 12
replace party_ideology= 4 if  prtvtcbg == 1
replace party_ideology= 4 if  prtvtcbg == 3
replace party_ideology= 4 if  prtvtcbg == 4
replace party_ideology= 4 if  prtvtcbg == 5
replace party_ideology= 4 if  prtvtcbg == 6
replace party_ideology= 4 if  prtvtcbg == 8
replace party_ideology= 4 if  prtvtcbg == 9
replace party_ideology= 4 if  prtvtdch == 3
replace party_ideology= 4 if  prtvtdch == 4
replace party_ideology= 4 if  prtvtdch == 7
replace party_ideology= 4 if  prtvtacy == 2
replace party_ideology= 4 if  prtvtacy == 3
replace party_ideology= 4 if  prtvtccz == 5
replace party_ideology= 4 if  prtvdde2 == 2
replace party_ideology= 4 if  prtvdde2 == 4
replace party_ideology= 4 if  prtvtcdk == 3
replace party_ideology= 4 if  prtvtcdk == 6
replace party_ideology= 4 if  prtvtcdk == 7
replace party_ideology= 4 if  prtvtdee == 1
replace party_ideology= 4 if  prtvtdee == 3
replace party_ideology= 4 if  prtvtdee == 7
replace party_ideology= 4 if  prtvtces == 1
replace party_ideology= 4 if  prtvtces == 3
replace party_ideology= 4 if  prtvtces == 7
replace party_ideology= 4 if  prtvtces == 10
replace party_ideology= 4 if  prtvtces == 12
replace party_ideology= 4 if  prtvtcfi == 1
replace party_ideology= 4 if  prtvtcfi == 2
replace party_ideology= 4 if  prtvtcfi == 5
replace party_ideology= 4 if  prtvtcfi == 9
replace party_ideology= 4 if  prtvtcfr == 3
replace party_ideology= 4 if  prtvtcfr == 10
replace party_ideology= 4 if  prtvtgb == 1
replace party_ideology= 4 if  prtvtgb == 11
replace party_ideology= 4 if  prtvtgb == 17
replace party_ideology= 4 if  prtvtdhu == 2
replace party_ideology= 4 if  prtvtdhu == 3
replace party_ideology= 4 if  prtvtdhu == 6
replace party_ideology= 4 if  prtvtaie == 2
replace party_ideology= 4 if  prtvtais == 2
replace party_ideology= 4 if  prtvtais == 5
replace party_ideology= 4 if  prtvtbit == 7
replace party_ideology= 4 if  prtvtbit == 8
replace party_ideology= 4 if  prtvtbit == 12
replace party_ideology= 4 if  prtvalt1 == 1
replace party_ideology= 4 if  prtvalt1 == 5
replace party_ideology= 4 if  prtvalt1 == 9
replace party_ideology= 4 if  prtvalt1 == 11
replace party_ideology= 4 if  prtvalt1 == 16
replace party_ideology= 4 if  prtvalt1 == 18
replace party_ideology= 4 if  prtvtenl == 4
replace party_ideology= 4 if  prtvtano == 7
replace party_ideology= 4 if  prtvtano == 9
replace party_ideology= 4 if  prtvtcpl == 2
replace party_ideology= 4 if  prtvtcpl == 3
replace party_ideology= 4 if  prtvtbpt == 10
replace party_ideology= 4 if  prtvtbse == 1
replace party_ideology= 4 if  prtvtbse == 2
replace party_ideology= 4 if  prtvtbse == 3
replace party_ideology= 4 if  prtvtbse == 5
replace party_ideology= 4 if  prtvtdsi == 4
replace party_ideology= 4 if  prtvtdsi == 5
replace party_ideology= 4 if  prtvtcsk == 1
replace party_ideology= 4 if  prtvtcsk == 2
replace party_ideology= 4 if  prtvtcsk == 4
replace party_ideology= 4 if  prtvtcsk == 5
replace party_ideology= 4 if  prtvtcsk == 6
replace party_ideology= 5 if  prtvtcbe == 4
replace party_ideology= 5 if  prtvtcbe == 7
replace party_ideology= 5 if  prtvtcbe == 11
replace party_ideology= 5 if  prtvtcbe == 15
replace party_ideology= 5 if  prtvtcbg == 10
replace party_ideology= 5 if  prtvtcbg == 11
replace party_ideology= 5 if  prtvtdch == 1
replace party_ideology= 5 if  prtvtdch == 9
replace party_ideology= 5 if  prtvtdch == 10
replace party_ideology= 5 if  prtvtdch == 12
replace party_ideology= 5 if  prtvtdch == 15
replace party_ideology= 5 if  prtvtdch == 17
replace party_ideology= 5 if  prtvtacy == 4
replace party_ideology= 5 if  prtvtccz == 3
replace party_ideology= 5 if  prtvdde2 == 6
replace party_ideology= 5 if  prtvdde2 == 7
replace party_ideology= 5 if  prtvtcdk == 5
replace party_ideology= 5 if  prtvtcdk == 8
replace party_ideology= 5 if  prtvtdee == 8
replace party_ideology= 5 if  prtvtdee == 10
replace party_ideology= 5 if  prtvtcfi == 6
replace party_ideology= 5 if  prtvtcfi == 7
replace party_ideology= 5 if  prtvtcfi == 10
replace party_ideology= 5 if  prtvtcfr == 2
replace party_ideology= 5 if  prtvtcfr == 8
replace party_ideology= 5 if  prtvtgb == 12
replace party_ideology= 5 if  prtvtgb == 20
replace party_ideology= 5 if  prtvtdhu == 4
replace party_ideology= 5 if  prtvtdhu == 7
replace party_ideology= 5 if  prtvtais == 3
replace party_ideology= 5 if  prtvtbit == 9
replace party_ideology= 5 if  prtvtbit == 10
replace party_ideology= 5 if  prtvtbit == 13
replace party_ideology= 5 if  prtvalt1 == 2
replace party_ideology= 5 if  prtvalt1 == 12
replace party_ideology= 5 if  prtvalt1 == 15
replace party_ideology= 5 if  prtvtenl == 1
replace party_ideology= 5 if  prtvtenl == 3
replace party_ideology= 5 if  prtvtenl == 9
replace party_ideology= 5 if  prtvtano == 8
replace party_ideology= 5 if  prtvtcpl == 1
replace party_ideology= 5 if  prtvtcpl == 6
replace party_ideology= 5 if  prtvtbpt == 2
replace party_ideology= 5 if  prtvtbpt == 7
replace party_ideology= 5 if  prtvtbpt == 8
replace party_ideology= 5 if  prtvtbse == 10
replace party_ideology= 5 if  prtvtdsi == 3
replace party_ideology= 5 if  prtvtdsi == 10

label var party_ideology "Party's Ideology"
label define party_ideology 1 "Left" 2 "Center-Left" 3 "Center" 4 "Center-Right" 5 "Right"
label values party_ideology party_ideology
