asset_type: !!python/object/apply:__main__.AssetType
- prompt_template
content_hash: 6470c7db5c4d282b9c6cd3c8bf1b5e570cb16a0e277f7e1b494013c4220356d4
created_at: 2025-06-19 15:57:47.548558
development_path: research_workspaces/june_2025_research_dev_workspace/prompt_templates/direct_analysis
format_version: yaml_v1.0
name: template
storage_path: asset_storage/prompt_template/64/70/6470c7db5c4d282b9c6cd3c8bf1b5e570cb16a0e277f7e1b494013c4220356d4
validation_status: pending
version: auto
