content_hash: 6470c7db5c4d282b9c6cd3c8bf1b5e570cb16a0e277f7e1b494013c4220356d4
ingestion_date: '2025-06-19T15:57:47.549174'
ingestion_method: unified_asset_pipeline
source_path: research_workspaces/june_2025_research_dev_workspace/prompt_templates/direct_analysis
source_type: development_workspace
