* Encoding: UTF-8.

DATASET ACTIVATE DataSet3.
CROSSTABS
  /TABLES=Gender BY Groups
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN 
  /COUNT ROUND CELL.

MEANS TABLES=Age BY Groups
  /CELLS=MEAN COUNT STDDEV.

MEANS TABLES=Income BY Groups
  /CELLS=MEAN COUNT STDDEV.

MEANS TABLES=AMLO BY Groups
  /CELLS=MEAN COUNT STDDEV.

MEANS TABLES=Ideology BY Groups
  /CELLS=MEAN COUNT STDDEV.
