name: 🔬 Research Question
description: Methodological question or academic concern
title: "[RESEARCH] "
labels: ["research", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for methodological questions, statistical concerns, or academic research issues.

  - type: textarea
    id: question
    attributes:
      label: Research Question
      description: What methodological or academic question needs addressing?
      placeholder: Describe the research methodology concern or question
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Research Category
      description: What type of research question is this?
      options:
        - Statistical methodology
        - Framework validation
        - Experimental design
        - Data integrity
        - Reproducibility
        - Academic standards
        - Peer review preparation
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Research Context
      description: What experiment or framework does this relate to?
      placeholder: |
        - Experiment: MVA Experiment 3
        - Framework: CFF v4.1
        - Research domain: Computational social science
    validations:
      required: true

  - type: textarea
    id: implications
    attributes:
      label: Research Implications
      description: Why is this important for research validity?
      placeholder: |
        How does this affect:
        - Statistical validity
        - Research reproducibility  
        - Academic credibility
        - Peer review acceptance
    validations:
      required: true

  - type: textarea
    id: literature
    attributes:
      label: Relevant Literature
      description: Any relevant academic sources or standards?
      placeholder: Citations, methodological guidelines, or academic best practices
    validations:
      required: false

  - type: textarea
    id: proposed_approach
    attributes:
      label: Proposed Approach
      description: How might we address this research question?
      placeholder: Methodological suggestions or approaches to investigate
    validations:
      required: false 