"""add_statistical_comparison_tables

Revision ID: 58bd99eb37cd
Revises: d3dd30425826
Create Date: 2024-07-12 14:02:18.005391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58bd99eb37cd'
down_revision: Union[str, None] = 'd3dd30425826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('configuration', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistical_comparisons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('comparison_type', sa.String(length=50), nullable=False),
    sa.Column('source_job_ids', sa.String(), nullable=False),
    sa.Column('comparison_dimension', sa.String(length=50), nullable=False),
    sa.Column('similarity_metrics', sa.String(), nullable=True),
    sa.Column('significance_tests', sa.String(), nullable=True),
    sa.Column('confidence_intervals', sa.String(), nullable=True),
    sa.Column('similarity_classification', sa.String(length=50), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('text_content', sa.String(), nullable=True),
    sa.Column('text_identifier', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('prompt_template', sa.String(length=100), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('centroid_x', sa.Float(), nullable=False),
    sa.Column('centroid_y', sa.Float(), nullable=False),
    sa.Column('raw_scores', sa.String(), nullable=False),
    sa.Column('api_cost', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_results')
    op.drop_table('statistical_comparisons')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
