content_hash: 06b7e709c5db83e23fca491656a51d64831fa0194f0b0b0e1874ef1ef130612b
ingestion_date: '2025-06-19T15:57:47.543927'
ingestion_method: unified_asset_pipeline
source_path: research_workspaces/june_2025_research_dev_workspace/prompt_templates/moral_foundations_analysis
source_type: development_workspace
