content_hash: 08b33fff5a0e2453dc04e6d1ca8dfe33f62133d0216a7eae06d3595857ac2e77
ingestion_date: '2025-06-19T15:57:47.508977'
ingestion_method: unified_asset_pipeline
source_path: research_workspaces/june_2025_research_dev_workspace/frameworks/iditi
source_type: development_workspace
