#!/bin/bash
# Comprehensive LiteLLM Debug Suppression Environment Variables
# Generated by comprehensive_litellm_suppression.py

export LITELLM_VERBOSE='false'
export LITELLM_LOG='ERROR'
export LITELLM_LOG_LEVEL='ERROR'
export LITELLM_PROXY_DEBUG='false'
export LITELLM_PROXY_LOG_LEVEL='ERROR'
export LITELLM_PROXY_VERBOSE='false'
export LITELLM_PROXY_DEBUG_MODE='false'
export LITELLM_PROXY_LOG_LEVEL_DEBUG='false'
export JSON_LOGS='false'
export LITELLM_COLD_STORAGE_LOG_LEVEL='ERROR'
export DISCERNUS_LOG_LEVEL='WARNING'
export DISCERNUS_VERBOSE='false'

echo '✅ LiteLLM debug suppression environment variables loaded'
