asset_type: !!python/object/apply:__main__.AssetType
- prompt_template
content_hash: b73e2d819e8865aa5f126913046c5f206981e6df7558dfad8752eb7fed002dbf
created_at: 2025-06-19 15:57:47.555043
development_path: research_workspaces/june_2025_research_dev_workspace/prompt_templates/hierarchical_analysis
format_version: yaml_v1.0
name: template
storage_path: asset_storage/prompt_template/b7/3e/b73e2d819e8865aa5f126913046c5f206981e6df7558dfad8752eb7fed002dbf
validation_status: pending
version: auto
