content_hash: b73e2d819e8865aa5f126913046c5f206981e6df7558dfad8752eb7fed002dbf
ingestion_date: '2025-06-19T15:57:47.555695'
ingestion_method: unified_asset_pipeline
source_path: research_workspaces/june_2025_research_dev_workspace/prompt_templates/hierarchical_analysis
source_type: development_workspace
